---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-0
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block-ec
