---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: homelab
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: github-webhook-token-secret
  resources:
    - kind: GitRepository
      name: flux-system
    - kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      name: flux
    - kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      name: cluster
    - kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      name: workloads
    - kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      name: core
    - kind: Kustomization
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      name: crds
