---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - helm-release.yaml
commonLabels:
  app.kubernetes.io/name: smtp-relay
  app.kubernetes.io/instance: smtp-relay
