---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-alert-manager
  namespace: flux-system
spec:

  interval: 10m
  path: "./k8s/workloads/monitoring/alert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cluster-workloads-external-secrets-stores
    - name: cluster-workloads-rook-ceph-cluster
