---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.50.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    deploymentStrategy:
      type: Recreate
    replicas: 1
    rbac:
      pspEnabled: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
      GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
      GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
      GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
      GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
      GF_AUTH_GOOGLE_CLIENT_ID: "${SECRET_GOOGLE_OAUTH_CLIENT_ID}"
      GF_AUTH_GOOGLE_CLIENT_SECRET: "${SECRET_GOOGLE_OAUTH_CLIENT_SECRET}"
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN_CASA}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth:
        oauth_auto_login: true
      users:
        auto_assign_org: true
        auto_assign_org_role: Admin
      auth.basic:
        enabled: false
        disable_login_form: true
      auth.google:
        enabled: true
        scopes: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
        auth_url: "https://accounts.google.com/o/oauth2/auth"
        token_url: "https://accounts.google.com/o/oauth2/token"
        allowed_domains: "${SECRET_DOMAIN_2}"
        allow_sign_up: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        # list of datasources that should be deleted from the database
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-operated:9090/
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway:3100
    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/2842
        ceph-cluster:
          gnetId: 2842
          revision: 14
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5336
        ceph-osd:
          gnetId: 5336
          revision: 5
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/5342
        ceph-pools:
          gnetId: 5342
          revision: 5
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/14062
        smart:
          gnetId: 14062
          revision: 2
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/1860
        nodeexporter:
          gnetId: 1860
          revision: 23
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/14127
        metallb:
          gnetId: 14127
          revision: 1
          datasource: Prometheus
        unifi-client-insights:
          gnetId: 11315
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11311
        unifi-network-sites:
          gnetId: 11311
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11312
        unifi-usw-insights:
          gnetId: 11312
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/13665
        speedtest:
          gnetId: 13665
          revision: 1
          datasource: Prometheus
        blackbox:
          url: https://raw.githubusercontent.com/jr0dd/grafana-dashboards/main/blackbox.json
          datasource: Prometheus
        qbittorrent:
          url: https://raw.githubusercontent.com/esanchezm/prometheus-qbittorrent-exporter/master/grafana/dashboard.json
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
        radarr:
          url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/radarr.json
          datasource: Prometheus
        sonarr:
          url: https://raw.githubusercontent.com/k8s-at-home/grafana-dashboards/main/sonarr.json
          datasource: Prometheus
        cilium-agent:
          gnetId: 15513
          revision: 1
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/15514
        cilium-operator:
          gnetId: 15514
          revision: 1
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/15515
        cilium-hubble:
          gnetId: 15515
          revision: 1
          datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
      hosts:
        - "grafana.${SECRET_DOMAIN_CASA}"
      tls:
        - hosts:
            - "grafana.${SECRET_DOMAIN_CASA}"
    serviceAccount:
      create: true
      autoMount: true
    persistence:
      enabled: false
      storageClassName: rook-ceph-block
      size: 10Gi
      accessModes:
        - ReadWriteOnce
