# yamllint disable
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: test
#   namespace: default
# spec:
#   # storageClassName: ceph-block-ec
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# ---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: media
spec:
#  nodeSelector:
#    kubernetes.io/hostname: homelab-talos-0-worker-5

  containers:
    - name: myapp
      image: ubuntu:latest
      securityContext:
        privileged: true
      args:
        - "sleep"
        - "99999999999"
      volumeMounts:
#        - name: usb
#          mountPath: /dev/bus/usb
#       - name: old-media
#         mountPath: /old-media
       - name: media-cephfs
         mountPath: /media-cephfs
  volumes:
#    - name: usb
#      hostPath:
#        path: /dev/bus/usb
#    - name: old-media
#      nfs:
#        server: 10.250.0.200
#        path: /mnt/tank/media
    - name: media-cephfs
      persistentVolumeClaim:
        claimName: media-cephfs
#    - name: mount
#      persistentVolumeClaim:
#        claimName: home-assistant-config-v1
  restartPolicy: Always
