# yamllint disable
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: test
#   namespace: default
# spec:
#   # storageClassName: ceph-block-ec
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# ---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: media
spec:
#  nodeSelector:
#    kubernetes.io/hostname: homelab-talos-0-worker-0

  containers:
    - name: myapp
      image: ubuntu:latest
      securityContext:
        privileged: true
      args:
        - "sleep"
        - "99999999999"
      volumeMounts:
#       - name: backup
#         mountPath: /backup
       - name: test
         mountPath: /test
  volumes:
#    - name: backup
#      nfs:
#        server: 10.250.0.200
#        path: /mnt/tank/backups/softwarrself/plex-new
    - name: test
      persistentVolumeClaim:
        claimName: plex-trakt-sync-config
#    - name: mount
#      persistentVolumeClaim:
#        claimName: home-assistant-config-v1
  restartPolicy: Always
  tolerations:
  - key: "nuc"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
