---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "jellyfin-restore"
  namespace: "media"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "jellyfin-restic-secret"
    destinationPVC: "jellyfin-config-0"
    copyMethod: Direct
    storageClassName: ceph-block-ec
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 0
    # OR;
    # IMPORTANT NOTE:
    #   On bootstrap set `restoreAsOf` to the time the old cluster was destroyed.
    #   This will essentially prevent volsync from trying to restore a backup
    #   from a application that started with default data in the PVC.
    #   Do not restore snapshots made after the following RFC3339 Timestamp.
    #   date --rfc-3339=seconds (--utc)
    # restoreAsOf: "2023-01-21T16:00:00-05:00"
