---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
commonLabels:
  app.kubernetes.io/name: zigbee2mqtt
  app.kubernetes.io/instance: zigbee2mqtt
