---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-exporter-apc-ups
  namespace: monitoring
spec:
  interval: 15m
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  values:
    fullnameOverride: snmp-exporter-apc-ups
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"

    podAnnotations:
      configmap.reloader.stakater.com/reload: snmp-exporter-apc-ups
      k8s.v1.cni.cncf.io/networks: snmp-homelab-static

    extraConfigmapMounts:
      - name: snmp-exporter-apc-ups
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-apc-ups
        readOnly: true
        defaultMode: 420

    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: apc-ups-0
          module:
            - apcups
          target: "10.240.239.5"
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
