---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - config-map.yaml
  - helm-release.yaml
  - prometheus-rule.yaml
  - net-attach.yaml
configMapGenerator:
  - name: apc-ups-dashboard
    files:
      - apc-ups-dashboard.json=./dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
labels:
  - pairs:
      app.kubernetes.io/name: snmp-exporter-apc-ups
      app.kubernetes.io/instance: snmp-exporter-apc-ups
