---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.11.1@sha256:151f4921ba9960969df663a21dada1bd63e46e76ceaaa2194b6b437a2bd66f77

    service:
      main:
        ports:
          http:
            port: 8181

    env:
      TZ: "${TZ}"

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: &host "tautulli.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-v1
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/backups/softwarrself/tautulli
        mountPath: /config/backups
        readOnly: false

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
