---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-test
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 30m
  values:
    controller:
      replicaCount: 3

      updateStrategy:
        type: RollingUpdate

      publishService:
        enabled: true

      ingressClassResource:
        default: true

      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true"
        enable-real-ip: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000

      metrics:
        enabled: false #TODO
        serviceMonitor:
          enabled: false #TODO

      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: ingress-nginx
              app.kubernetes.io/component: controller

      resources:
        requests:
          cpu: 23m
          memory: 249M
        limits:
          memory: 312M
