---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 300
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 300
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.28.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: prometheus
    alertmanager:
      enabled: false

    kubeApiServer:
      enabled: true

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance

    kubeProxy:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      metricLabelsAllowlist:
        - "persistentvolumeclaims=[*]"
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
      resources:
        requests:
          cpu: 15m
          memory: 127M
        limits:
          memory: 153M

    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          memory: 64M
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node

    grafana:
      enabled: false
      forceDeployDashboards: true
      sidecar:
        dashboards:
          multicluster:
            etcd:
              enabled: true

    prometheusOperator:
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            memory: 100Mi
    prometheus:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "prometheus.${SECRET_DOMAIN_CASA}"
        tls:
          - hosts:
              - "prometheus.${SECRET_DOMAIN_CASA}"
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      prometheusSpec:
        resources:
          requests:
            cpu: 150m
            memory: 2Gi
          limits:
            memory: 8Gi
        replicas: 3
        replicaExternalLabelName: __replica__ # must match with thanos value `.query.replicaLabel[0]`
        # Breaks any metric that has an existing "cluster" label on a metric
        # externalLabels:
        #   cluster: home # must match with thanos value `.ruler.clusterName`
        thanos:
          image: quay.io/thanos/thanos:v0.31.0
          objectStorageConfig:
            name: thanos-objstore-secret
            key: objstore.yml
        ruleSelectorNilUsesHelmValues: false
        podAntiAffinity: hard
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 2d
        retentionSize: 20GB
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "ceph-block-ec"
              resources:
                requests:
                  storage: 20Gi
        additionalScrapeConfigs:
          - job_name: ceph-exporter
            scrape_interval: 1m
            scrape_timeout: 10s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "nuc1.${SECRET_DOMAIN_INTERNAL}:9283"
                  - "nuc2.${SECRET_DOMAIN_INTERNAL}:9283"
                  - "nuc3.${SECRET_DOMAIN_INTERNAL}:9283"
                  - "pve-lilslim.${SECRET_DOMAIN_INTERNAL}:9283"
                  - "pve-fatman.${SECRET_DOMAIN_INTERNAL}:9283"
          - job_name: pve-node-exporter
            scrape_interval: 1m
            scrape_timeout: 10s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "nuc1.${SECRET_DOMAIN_INTERNAL}:9100"
                  - "nuc2.${SECRET_DOMAIN_INTERNAL}:9100"
                  - "nuc3.${SECRET_DOMAIN_INTERNAL}:9100"
                  - "pve-lilslim.${SECRET_DOMAIN_INTERNAL}:9100"
                  - "pve-fatman.${SECRET_DOMAIN_INTERNAL}:9100"
          - job_name: opnsense-node-exporter
            scrape_interval: 1m
            scrape_timeout: 10s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "opnsense.${SECRET_DOMAIN_INTERNAL}:9100"
