---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wasabi-volsync
  namespace: volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wasabi-volsync
    creationPolicy: Owner
  dataFrom:
    - extract:
        # S3_ACCESS_KEY, S3_SECRET_KEY, S3_INTERNAL_ENDPOINT
        key: wasabi-volsync
