---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
resources:
  - ./cronjob.yaml
  - ./externalsecret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: volsync-mirror
      app.kubernetes.io/instance: volsync-mirror
commonAnnotations:
  kustomize.toolkit.fluxcd.io/substitute: disabled
