---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
commonLabels:
  app.kubernetes.io/name: radarr
  app.kubernetes.io/instance: radarr
