---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - config-pvc.yaml
  - helm-release.yaml
configMapGenerator:
  - name: frigate
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: frigate
  app.kubernetes.io/instance: frigate
