---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-vector-aggregator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-loki
  path: ./k8s/workloads/monitoring/vector/aggregator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vector-aggregator
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-vector-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-vector-aggregator
  path: ./k8s/workloads/monitoring/vector/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vector-agent
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
