---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - helm-release.yaml
commonLabels:
 app.kubernetes.io/name: intel-gpu-plugin
 app.kubernetes.io/instance: intel-gpu-plugin
