---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: ${GATEWAY_ADDRESS}
        peer-asn: 64513
        my-asn: 64513
    address-pools:
      - name: default
        protocol: bgp
        avoid-buggy-ips: true
        addresses:
          - ${CILIUM_BGP_LB_RANGE}
