---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-scrypted
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-rook-ceph-cluster
    - name: cluster-workloads-volsync
  path: ./k8s/workloads/home/scrypted/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
