---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-cephfs
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: rook-cephfs-media
