---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alert-manager
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alert-manager
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: alert-manager
