---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.13.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: external-dns
    interval: "5m"
    # logLevel: debug
    sources:
      - ingress
      - service
      - crd
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-api-token
      email: "${SECRET_EMAIL_CLOUDFLARE}"
      proxied: true
    policy: sync
    txtPrefix: "k8s-${CLUSTER_NAME}."
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN_CASA}"
    crd:
      create: false
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
