# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token
    namespace: networking
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:0yzi3h246LlReSKMXVd2lB6PF8zBCImdvDshMRJ6F02qhfTLutdxLQ==,iv:R74tWc/t8YNdbHh8RyunNQHpG9tGA+GvZ+hipxdVMXU=,tag:TYLKArfPgo3DjtAA/FPVcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWmx1bFE4dktpSHZDRVVv
            NXk3WkVwVW9RcDkzYXMyRGtNSExSa2cvazBBCjU3bmlwdmw0QnRWdVM2NmRNTjNS
            ekxCaWZPZy9ZRXdZak1BNTNjSC9mZTAKLS0tIEdOT2N0Y3JmekNXeDgyQUExUWN0
            aWlmS2xDRmJ3em5GMlF1SzF1SGxaZ2MK5IK4UqI1Vlxee1qqEna1nI99Vlqi2q7i
            Qo8cSlnPwKNdVuMPUoqGqoXtqZmnH4qsHWxKxpNSe729tGT86Q8ASw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-07T17:31:15Z"
    mac: ENC[AES256_GCM,data:hbsaT/FPALqNV1U1CbftikcqO/S7lzj92oWqZvA+NNEsdwTy5UUxVERBwO0KEWyqKO2MkPm3kGZVkolEfJQNlWJZxWhqnKlFk5uZoLbv/gz3c4L749GJx4sirMhTFcz+bxKhVmq5bxnsOIH994lB2HHsb4XXKld7IU8jz0dwTxE=,iv:zKBqY9GYWS/tQ5waUVLamsCJ45iZ4L/9vFjvXQcgoQA=,tag:7GSfi9ogN4MHQXPyA4D61A==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
