---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - helm-release.yaml
  - backup-job.yaml
commonLabels:
  app.kubernetes.io/name: calibre-web
  app.kubernetes.io/instance: calibre-web
