---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin-backup
  namespace: media
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 300
      template:
        spec:
          tolerations:
            - key: "nuc"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: ghcr.io/bjw-s/pmb:v0.4.0@sha256:10388afc2a2f6a9f2ae7ec15aee5d919c3d274fd862c753abd6a91f656bf6958
              imagePullPolicy: Always
              securityContext:
                privileged: true
              env:
                - name: KOPIA_PASSWORD
                  value: "${KOPIA_PASSWORD}"
              volumeMounts:
                - name: data
                  mountPath: /data/src
                - name: backup
                  mountPath: /data/dest
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: jellyfin-config-v1
            - name: backup
              nfs:
                server: "${TRUENAS_VM_ADDRESS}"
                path: /mnt/tank/backups/softwarrself/jellyfin
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - jellyfin
                  topologyKey: kubernetes.io/hostname
