---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - backup-job.yaml
  - net-attach.yaml
commonLabels:
  app.kubernetes.io/name: jellyfin
  app.kubernetes.io/instance: jellyfin
