---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - trakt-sync-cron.yaml
  - trakt-sync-pytrakt-secret.yaml
  - trakt-sync-env-secret.yaml
  - backup-job.yaml
  - net-attach.yaml
commonLabels:
  app.kubernetes.io/name: plex
  app.kubernetes.io/instance: plex
