---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: rook-ceph-block
