# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plex-trakt-sync-pytrakt-json
    namespace: media
stringData:
    .pytrakt.json: ENC[AES256_GCM,data:goFyD+PKf9GrWW+PTDjJ/0dg8jWHwwwF6AIM+sHWq7VZddReUSOeAJad7d8tTYMvQuCgrdBse6L1D8Le47w4XwBstt9aMz6BUoJlHxGd0FNzT914MKNjtAae2TdKXzTArdmdWjdLLPfUR16htNtcZ0WAP6WexfMk88kcUGzlOfwxLAGGJtkdbIguri111+Jk8FdLEvok0d7vChSHGRNuHtAT3wkj0FbGTHkz6mz+PcbzlBq2csgQ8ZfQ18+Py8ccE3XdnJZbvwxmX+i6NbGRi4R9TswOq2RXfl3N+Ng8GwB0z1khV3GqcfDPk1o/34ueEkyKdblz3mXD4lBKmW687yui+WDT74+7lvgXkhNe0jEB2vFAZP+xpyFJZ4vZTCSz2JfvlSnek2W6PNhYzKfVIpMs+SszBnYSM9TXszI2oJelL06SlZOSLCh3ZPr1NUU1s3YWcnhJ3IFF57ybgYt+kVKnphf11qQx4K/z/lH1bg==,iv:kal6DlSCav4YnJubHRvuNVab+4+iZVDsxzFa1AN7yac=,tag:LAbbzzKr+M6k7upz57xy7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUzNPdlFhVFdESHN6QkN6
            ZmdRaStVVGN4WUZPdWY3blkxOUhkNXgyakhFCncvWS8yTi9WR2J1QTlpcmdXOGVt
            T21ZckZ0YmZuMXFHaHhZSkJvNWxhS1kKLS0tIE5zM2s0czdoMElRa1kvTHUzN1Fk
            SWZhZEV2T1FUekNmdE5JTjRaZko4aVEKrRDIof6SeEU/HqH+jtH35NLJpYF4709l
            UF5YbgNSpd0DPpRpVZeocBqsoIV830EmLc/0wgXRMNFuDtp1/TJGkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-26T20:17:32Z"
    mac: ENC[AES256_GCM,data:eQlDJVSp1Ttgmq1BzIjYTewbrB7OjcLLyV3mL0rnGBEwjJDzye4wGmJyhtlyeB0jpDMY6E0ewa7DFcqqGCXyuxS0Vxd8j3BmbkcDAPlBweSqW9L50pBf0ERxL08jbzcGiPCxoGTxp1897GQeQUmpg+QEy4J9rgpkmqLBpv8JX6g=,iv:j8AamXRSl+6tyH161F+3kgC5Wnxmt/xuu5MoKvsbCe4=,tag:Ev+8BXkj6E3uhgpbpnr6Cg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.1
