---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - secret-creds.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: cloudflared
