# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
stringData:
    cred.json: ENC[AES256_GCM,data:cwY/WH19y5Eaml2D1NhMs060KvzuM3R8AS8+LGnli/HrA/DDuBy+J3E5hHJ0MNtJ1ciWHsgWr1nOAzMMy32VinbHnONzy/hfZTXB9J4mawGtji+ZKWJ34R8TJqhkL1srk3r7st8h9i4VNN2uUGnpgnoozUFowgvx7MB2vYRRDWw0UxJUgvdoMzvkPvkpt5J4Q3K2Wd9prhNi5LumetwGLgdRCHjXW1DFEezeacHK4NfRh85li5skBA==,iv:RqXHpMAvdCq4ev06cVbYiW3zSiajCQE+F3TLOB73erg=,tag:fbQbdYvOlV07QwPVYgSliQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRUVncERDZ3dxdVZXWUw3
            cm5lL3ZVMG0xd0ZTOGcxcm5TbWlhV1VDc0VVCndLY0lxbGdNVnp5OUxZaTZ0WUQ5
            elRiRE1oS0Roajh0K1Bpc2o0U211cTQKLS0tIHZKQmc2cHEzbTcwbVgyQ1J6MUht
            eWN3eTd1Z3VVZHFRb2NWVEhQRE1YOUUKnuQn+xfBan4SsMMaPGSW/PQYek519ef7
            AdQ81m35wQpNENtMBx0tAOIQKVXyJu7fKiAMkFzJ4MiyyVo0qWotdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T12:11:32Z"
    mac: ENC[AES256_GCM,data:tsKYqNgC1UhQCNNkqR6puqSwdt6rtwstNOwNxkt+g5mxptVMVfhGQREXVSrXh+DqlQGBWk7cTBymAioe82sM8jAapxEHeybktm6nIq4Qz8rKfPVcADBdWNuc/53oMLJZTVWbvAFJkfpbYxuYRvZfcM9VYzV7eb97xL62cShaAds=,iv:PhnazPWGwwV/2M1+6RXf0xRaHjYDcvhlANkfSZUoZa8=,tag:kLZOYEFEiP6qx/ZyHHfOQA==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
