# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
stringData:
    credential.json: ENC[AES256_GCM,data:IIIrfUVifjX8sOX5QtwmXvklzmCSekAvC/D8eju/E3hflArbHMsZUatATZuSm1owV8SbtSBWcHoJXhQ0FdMLrrEauy2xmamPw2DRddO4vVlce0NFYG6AHCG27oMO7K0mBEJlfgGzhUG3V/fLq8PNAv6uDKvPTTaiU2LQMeL2/zDF9lgOOB23jt19F/d6jC3OenvgQbqJA1aZdSHTb8ZT0+rPjQ/hqmSB3vgXlTlwdRFsOJcAxM9mgRYPU2q/Qf6d4DS3vESK1UksVIUXQHw=,iv:TrSHl4Wls7loLMLQ1UW/gpiTU7YAHX+09reYSI1RjHk=,tag:qKaXfsVALn7CZo+ty9dquA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTE03bXhhU2tPTkFtR2x5
            Y1IzN2NnekdmeTdNSS9JYkptWDI2cXJRQWxZCjYvbkY2dnhSQkE4RmhFV1JVVGQv
            K1VNcDAxM3UxbzhtQ0F4dWZYYlRPc1UKLS0tIEQvMG9odEJNaTJ3ZC9RbDRsYlZv
            OGI3V1JkZFdRZ0xrczZkclpJU3ZQeXcKF5zC5PdRxeDnTsoh3Hgrx8y1QPxgskp/
            +o4Ue1zUd4+a+1oK16IYfInU74R8GmlgHn7aIOJNh7g8/LYg7gk/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-08T11:46:20Z"
    mac: ENC[AES256_GCM,data:LjPnwSx/GaYN20kGefcReIVJW+uTMORCiwcCzsYvseQ1bfILdLuE31/eIadrKzuMF0dxXefHn6Nmxt6a4d3tZL/6uqK/O2RvaNJTeGKw6BuEdgfKY1oGISpqvXfdhv0M5lICdiaJt2FiKE711nEEdKYoRk5j2QTlJ9KxMeXyWl0=,iv:Qlz1V+z8ezaUIUiTvD2r8coFFf8xqBsbQdS1QeX6e9o=,tag:uFCYxqYDAFNnh4YtNBHINQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
