# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
stringData:
    credential.json: ENC[AES256_GCM,data:lmNWjHeM1bUGUSP+tJTjR0srxwrMOY0gHq22K85vHzg4LXbaFTnFnqfjxqwcWVFA3HcErQ0+d6ATMli+O51rd6Vr5lM+sugGi1odsipO8YfmeyKjP1tF/4NL8ElOidAkxiktsdIK32lJrdB9XD+vdiLdFUnKTLDsj1oi8/OHYRT6EaKIcPKnBsCSNaapHSVQ22IPFA39qxJMTltkQwvLp6HwH6F4EW5fyjkYSt2M6T1WnLQBKyg=,iv:TzvEYuVRugErxsTn2e6Txo2Ve3T++oMSR2XwrViUZf4=,tag:1qLFByleiIqOijRalGVT3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcWpLWkJEdXU4QTJBTG1n
            QTljRll6L1FCalhxMk1mbHBFalY3R2JIdERZCjAwcFdRM3BKY0tuSFpHWnY5cGhN
            N2MxWDZGWjl5VDFTYXRsTnRFcG5hSk0KLS0tIDlMV29SSlBHQ0djVmFrVWxra1k1
            U2RHS0xtQURpMk5sazkyTVVHUWtHNzAKreUBeagftuNx679mKLhOeHspgY7VoWdb
            fAPWzq2ls3F99xNeH3Ol2YYPXvoWpeeN/pogeNj9C6ZGvhE5PcH98g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-07T16:34:26Z"
    mac: ENC[AES256_GCM,data:XOGbroFfF8g1Yz7LlTgqRaG6eQSGgBCwel6XZIK8F8bozeBqW2iR0i+/h8aC7n5vNpz8LNpuv0jHS0Dsf9M2F4rP7tzZ4TiO7dVgdYPRToQFBICmuKO36POrKp1ohjYIKA5z5MBzL1GTD5zF87gNzHdpHOat7A/x4fX6t837HZ0=,iv:I7kdhcAcHudow1M4afm18RaxPZHtUcWtcJCUFpr62ho=,tag:NMhH3kyicJZlAW7mJPiueQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
