---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-nvr-recordings-cephfs
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Ti
  storageClassName: rook-cephfs-media
