---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - service-monitor.yaml
commonLabels:
  app.kubernetes.io/name: intel-gpu-exporter
  app.kubernetes.io/instance: intel-gpu-exporter
