---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - helm-release.yaml
labels:
 - pairs:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter
