---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: qbittorrent
  app.kubernetes.io/instance: qbittorrent
#configMapGenerator:
#  - name: qbittorrent-config
#    files:
#      - config/categories.json
#      - config/qBittorrent.conf
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - backup-job.yaml
  - tag-tracker-errors
  - net-attach.yaml
