---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-workloads-plexautolanguages
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-workloads-plex
  path: ./k8s/workloads/media/plexautolanguages/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
