---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: "2m"
    # logLevel: debug
    sources:
      - ingress
      - crd
    policy: sync
    txtPrefix: "k8s-${CLUSTER_NAME}."
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN_CASA}"
    extraArgs:
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: api-token
    rbac:
      additionalPermissions:
        - apiGroups: ["externaldns.k8s.io"]
          resources: ["dnsendpoints"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["externaldns.k8s.io"]
          resources: ["dnsendpoints/status"]
          verbs: ["*"]
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
