---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helm-release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/instance: external-dns
