---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./cloudflared/ks.yaml
  - ./external-dns/ks.yaml
  - ./multus/ks.yaml
  - ./traefik/ks.yaml
  - ./k8s-gateway/ks.yaml
  - wildcard-certificate
  - opnsense
  - external-svc
