---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-ceph-block
